<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('members')->insert([
            [
                'pedigree' => 1,
                'parent_id' => null,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 1',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 2,
                'parent_id' => 1,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 2',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 3,
                'parent_id' => 2,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 3',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 4,
                'parent_id' => 3,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 4',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 5,
                'parent_id' => 4,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 5',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 6,
                'parent_id' => 5,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 6',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 7,
                'parent_id' => 6,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 7',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 8,
                'parent_id' => 7,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 8',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 9,
                'parent_id' => 8,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 9',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 10,
                'parent_id' => 9,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 10',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 11,
                'parent_id' => 10,
                'couple_id' => null,
                'ordinal_brother' => 1,
                'marriage_step' => null,
                'name' => 'Nguyễn Hệ 11',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            [
                'pedigree' => 12,
                'parent_id' => 11,
                'couple_id' => null,
                'ordinal_brother' => 6,
                'marriage_step' => null,
                'name' => 'Nguyễn Trường Tứ',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            //13
            [
                'pedigree' => 13,
                'parent_id' => 12,
                'couple_id' => null,
                'ordinal_brother' => 4,
                'marriage_step' => null,
                'name' => 'Nguyễn Đình Hiệp',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 14
            [
                'pedigree' => 13,
                'parent_id' => null,
                'couple_id' => 13,
                'ordinal_brother' => null,
                'marriage_step' => 1,
                'name' => 'Nguyễn Thị Hoa',
                'gender' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 15
            [
                'pedigree' => 14,
                'parent_id' => 13,
                'couple_id' => null,
                'ordinal_brother' => 2,
                'marriage_step' => 1,
                'name' => 'Nguyễn Trường Thọ',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 16
            [
                'pedigree' => 14,
                'parent_id' => 13,
                'couple_id' => null,
                'ordinal_brother' => 3,
                'marriage_step' => 1,
                'name' => 'Nguyễn Trường Thành',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 17
            [
                'pedigree' => 13,
                'parent_id' => 12,
                'couple_id' => null,
                'ordinal_brother' => 5,
                'marriage_step' => null,
                'name' => 'Nguyễn Đình Lực',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 18
            [
                'pedigree' => 13,
                'parent_id' => null,
                'couple_id' => 17,
                'ordinal_brother' => null,
                'marriage_step' => 1,
                'name' => 'Nguyễn Thị Thuận',
                'gender' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 19
            [
                'pedigree' => 14,
                'parent_id' => 17,
                'couple_id' => null,
                'ordinal_brother' => 2,
                'marriage_step' => 1,
                'name' => 'Nguyễn Thanh Tuấn',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 20
            [
                'pedigree' => 14,
                'parent_id' => 17,
                'couple_id' => null,
                'ordinal_brother' => 3,
                'marriage_step' => 1,
                'name' => 'Nguyễn Trường Vũ',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 21
            [
                'pedigree' => 13,
                'parent_id' => 12,
                'couple_id' => null,
                'ordinal_brother' => 2,
                'marriage_step' => null,
                'name' => 'Nguyễn Trường Hà',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 22
            [
                'pedigree' => 13,
                'parent_id' => null,
                'couple_id' => 21,
                'ordinal_brother' => null,
                'marriage_step' => 1,
                'name' => 'Nguyễn Thị Toàn',
                'gender' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 23
            [
                'pedigree' => 14,
                'parent_id' => 21,
                'couple_id' => null,
                'ordinal_brother' => 2,
                'marriage_step' => 1,
                'name' => 'Nguyễn Thị Thanh Thúy',
                'gender' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 24
            [
                'pedigree' => 14,
                'parent_id' => 21,
                'couple_id' => null,
                'ordinal_brother' => 3,
                'marriage_step' => 1,
                'name' => 'Nguyễn Trường Thi',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 25
            [
                'pedigree' => 13,
                'parent_id' => null,
                'couple_id' => 21,
                'ordinal_brother' => null,
                'marriage_step' => 2,
                'name' => 'Nguyễn Thị Châu',
                'gender' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 26
            [
                'pedigree' => 14,
                'parent_id' => 21,
                'couple_id' => null,
                'ordinal_brother' => 4,
                'marriage_step' => 2,
                'name' => 'Nguyễn Trường Hạnh',
                'gender' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
            // 27
            [
                'pedigree' => 14,
                'parent_id' => 21,
                'couple_id' => null,
                'ordinal_brother' => 5,
                'marriage_step' => 2,
                'name' => 'Nguyễn Thị Diễm Phúc',
                'gender' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'modified_by' => 1,
            ],
        ]);
    }
}
