---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fmdabhrf/public_html

    # Lấy code mới nhất
    - /usr/local/cpanel/3rdparty/bin/git pull origin main

    # Cài đặt thư viện PHP qua composer (không tải package dev để nhẹ hơn)
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH

    # Set quyền thư mục
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;

    # Laravel (nếu có): clear & cache lại
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
