---
deployment:
  tasks:
    # 1. Khai báo thư mục public_html
    - export DEPLOYPATH=/home/fmdabhrf/public_html/

    # 2. Copy toàn bộ code từ repo sang public_html, bỏ .git và .cpanel.yml
    - /bin/rsync -a --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH

    # 3. Di chuyển vào thư mục public_html để chạy lệnh
    - cd $DEPLOYPATH

    # 4. Cài đặt dependencies (nếu host có Composer)
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # 5. Thiết lập quyền ghi cho storage và bootstrap/cache
    - chmod -R 775 storage bootstrap/cache

    # 6. Clear & cache cấu hình Laravel
    - php artisan config:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
